### ISSUE TITLE
Supported Printers

### ISSUE THREAD

**Issue by VamsiTelagathoti** [CesarBalzer/Cordova-Plugin-BTPrinter#49]
it will be very Helpful , if all supported printers are mentioned here. Specially I am looking for printers in Zebra company. Can anyone tell me model names of the printer in Zebra Company .

Thanks in Advance. @CesarBalzer @andreszs

**Comment by VamsiTelagathoti** [comment]
In zebra printer it is showing printing is done but  nothing is happening at the printer side, Any one faced this issue? @andreszs @CesarBalzer

**Comment by andreszs** [comment]
The plugin uses standard [EPSON ESC/POS commands](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=2), so as long as the printer supports them (properly) this plugin will work correctly.

If your printer does not respond properly to standard commands, refer to its technical manual for the ESC/POS commands for each method and send them from the app with the plugin's `printPOSCommand` method.

It's not feasible to make a list of supported printers because there are thousands of them.

**Comment by VamsiTelagathoti** [comment]
Thank You @andreszs for your response , I got the desired output. It's working with the ZQ320 Printer.
